---
blueprint:
  name: Naprawiony Pilot Livarno TS1001
  description: Wersja z szerokim selektorem dla Zigbee2MQTT
  domain: automation
  input:
    remote:
      name: Pilot
      description: Wybierz swoje urządzenie (SW SALON table)
      selector:
        device:
          integration: mqtt
          model: TS1001
    light_target:
      name: Światło
      selector:
        target:
          entity:
            domain: light
trigger:
  - platform: device
    domain: mqtt
    device_id: remote
    type: action
    subtype: on
    id: wlacz
action:
  - choose:
      - conditions:
          - condition: trigger
            id: wlacz
        sequence:
          - service: light.toggle
            target: light_target
