blueprint:
  name: Lidl TS1001 – Zigbee2MQTT Remote
  description: Obsługa pilota Lidl / Silvercrest TS1001 przez Zigbee2MQTT
  domain: automation
  input:
    remote:
      name: Pilot TS1001 (Z2M)
      description: Wybierz encję action z Zigbee2MQTT
      selector:
        entity:
          domain: sensor
          multiple: false

    button_1_single:
      name: Przycisk 1 – Single
      default: []
      selector:
        action: {}

    button_1_double:
      name: Przycisk 1 – Double
      default: []
      selector:
        action: {}

    button_1_hold:
      name: Przycisk 1 – Hold
      default: []
      selector:
        action: {}

    button_1_release:
      name: Przycisk 1 – Release
      default: []
      selector:
        action: {}

    button_2_single:
      name: Przycisk 2 – Single
      default: []
      selector:
        action: {}

    button_2_double:
      name: Przycisk 2 – Double
      default: []
      selector:
        action: {}

    button_2_hold:
      name: Przycisk 2 – Hold
      default: []
      selector:
        action: {}

    button_2_release:
      name: Przycisk 2 – Release
      default: []
      selector:
        action: {}

    button_3_single:
      name: Przycisk 3 – Single
      default: []
      selector:
        action: {}

    button_3_double:
      name: Przycisk 3 – Double
      default: []
      selector:
        action: {}

    button_3_hold:
      name: Przycisk 3 – Hold
      default: []
      selector:
        action: {}

    button_3_release:
      name: Przycisk 3 – Release
      default: []
      selector:
        action: {}

    button_4_single:
      name: Przycisk 4 – Single
      default: []
      selector:
        action: {}

    button_4_double:
      name: Przycisk 4 – Double
      default: []
      selector:
        action: {}

    button_4_hold:
      name: Przycisk 4 – Hold
      default: []
      selector:
        action: {}

    button_4_release:
      name: Przycisk 4 – Release
      default: []
      selector:
        action: {}

mode: single

trigger:
  - platform: state
    entity_id: !input remote

action:
  - choose:
      - conditions: "{{ trigger.to_state.state == 'button_1_single' }}"
        sequence: !input button_1_single

      - conditions: "{{ trigger.to_state.state == 'button_1_double' }}"
        sequence: !input button_1_double

      - conditions: "{{ trigger.to_state.state == 'button_1_hold' }}"
        sequence: !input button_1_hold

      - conditions: "{{ trigger.to_state.state == 'button_1_release' }}"
        sequence: !input button_1_release

      - conditions: "{{ trigger.to_state.state == 'button_2_single' }}"
        sequence: !input button_2_single

      - conditions: "{{ trigger.to_state.state == 'button_2_double' }}"
        sequence: !input button_2_double

      - conditions: "{{ trigger.to_state.state == 'button_2_hold' }}"
        sequence: !input button_2_hold

      - conditions: "{{ trigger.to_state.state == 'button_2_release' }}"
        sequence: !input button_2_release

      - conditions: "{{ trigger.to_state.state == 'button_3_single' }}"
        sequence: !input button_3_single

      - conditions: "{{ trigger.to_state.state == 'button_3_double' }}"
        sequence: !input button_3_double

      - conditions: "{{ trigger.to_state.state == 'button_3_hold' }}"
        sequence: !input button_3_hold

      - conditions: "{{ trigger.to_state.state == 'button_3_release' }}"
        sequence: !input button_3_release

      - conditions: "{{ trigger.to_state.state == 'button_4_single' }}"
        sequence: !input button_4_single

      - conditions: "{{ trigger.to_state.state == 'button_4_double' }}"
        sequence: !input button_4_double

      - conditions: "{{ trigger.to_state.state == 'button_4_hold' }}"
        sequence: !input button_4_hold

      - conditions: "{{ trigger.to_state.state == 'button_4_release' }}"
        sequence: !input button_4_release
